apiVersion: broker.amq.io/v2alpha4
kind: ActiveMQArtemis
metadata:
  name: ex-aao
spec:
  deploymentPlan:
    size: 1
    image: quay.io/artemiscloud/activemq-artemis-broker-kubernetes:0.2.1
    initImage: <YOUR_IMAGE>_REGISTRY>/<YOUR_NAMESPACE>/custom-activemq-artemis-broker-init:0.0.1-ocp-0.2.3